Import Upstream version 10.8.0.1-1

diff --git a/Esm/runmake b/Esm/runmake
--- a/Esm/runmake
+++ b/Esm/runmake
@@ -1,7 +1,7 @@
 #!/bin/bash
 # BEGIN_ICS_COPYRIGHT8 ****************************************
 # 
-# Copyright (c) 2015, Intel Corporation
+# Copyright (c) 2015-2017, Intel Corporation
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -202,6 +202,16 @@ then
 fi
 
 echo "---------------------------------------"
+# Import OPA Build feature settings.
+export OPA_FEATURE_SET=${OPA_FEATURE_SET:-$(cat $TL_DIR/$PROJ_FILE_DIR/DEFAULT_OPA_FEATURE_SET)}
+FEATURE_SETTINGS_FILE=opa_feature_settings.${PRODUCT}.$BUILD_CONFIG
+$TL_DIR/OpaBuildFeatureToggles/opa_build_import_feature_settings.sh
+if [ -e ./$FEATURE_SETTINGS_FILE ]; then
+	. ./$FEATURE_SETTINGS_FILE
+else
+	echo "$0: ERROR: OPA BUILD - $FEATURE_SETTINGS_FILE not found" >&2
+	exit 1
+fi
 showenv
 echo "---------------------------------------"
 
@@ -245,7 +255,26 @@ then
 	#fi
 fi
 
-rm -rf $TL_DIR/$PROJ_FILE_DIR/packaged_files $TL_DIR/$PROJ_FILE_DIR/dist_files
+rm -rf $TL_DIR/$PROJ_FILE_DIR/packaged_files $TL_DIR/$PROJ_FILE_DIR/dist_files $TL_DIR/buildFeatureDefs
+
+
+# make sure buildFeatureDefs is in place for the build
+make -f Makefile.linux $TL_DIR/buildFeatureDefs || exit 1
+
+# make sure opafm_src.xml is in place for the build
+(cd ib/src/linux/startup;make opafm_src.xml) || exit 1
+
+# make sure files from BaseFiles are in place
+while read comp fn
+do
+	if [ "$comp" != "HFM" ]
+	then
+		continue
+	fi
+	dir=$(dirname $fn)
+	bn=$(basename $fn)
+	(cd $TL_DIR/$dir;make $bn) || exit 1
+done < $TL_DIR/Fd/BaseFiles
 
 args=
 if [ "$inplace" = y ]
@@ -259,7 +288,7 @@ fi
 
 if [ "$rpm" = y ]
 then
-	USE_UNIFDEF=${USE_UNIFDEF:-"no"}
+	USE_UNIFDEF=${USE_UNIFDEF:-"yes"}
 	set -x
 
 	# Pass env variables to rpmbuild. In integration build,
@@ -286,27 +315,66 @@ then
 	done
 	FILES_TO_TAR="$FILES_TO_TAR -T tar_inc_srcs_all"
 
-	RPMDIR="$TL_DIR/rpmbuild"
-	mkdir -p $RPMDIR/{BUILD,SPECS,BUILDROOT,SOURCES,RPMS,SRPMS}
+	if [ "$BUILD_PLATFORM_OS_VENDOR" != "ubuntu" ]
+	then
+		RPMDIR="$TL_DIR/rpmbuild"
+		mkdir -p $RPMDIR/{BUILD,SPECS,BUILDROOT,SOURCES,RPMS,SRPMS}
 
-	# Update the spec file
-	cp opa-fm.spec.base opa-fm.spec
-	sed -i "s/^Version:.*/Version: ${RPM_VER}/g" opa-fm.spec
-	sed -i "s/^Release:.*/Release: ${RPM_REL}%{?dist}/g" opa-fm.spec
-	# update distro dependencies
-	./update_opa-fm_spec.sh
-	mv opa-fm.spec $RPMDIR/SPECS/
+		# Update the spec file
+		cp opa-fm.spec.base opa-fm.spec
+		sed -i "s/__RPM_VERSION/${RPM_VER}/g" opa-fm.spec
+		sed -i "s/__RPM_RELEASE/${RPM_REL}%{?dist}/g" opa-fm.spec
+		# update distro dependencies
+		./update_opa-fm_spec.sh
+		mv opa-fm.spec $RPMDIR/SPECS/
 
-	# Create source tar ball. Update licenses if needed.
-	$TL_DIR/MakeTools/make_src_tar.sh "${RELEASE_TYPE}" "${TL_DIR}" "$USE_UNIFDEF" "$RPMDIR/SOURCES/opa-fm.tar.gz" "$FILES_TO_TAR" " -X tar_exc_pattern" || exit 1
+		# Create source tar ball. Update licenses if needed.
+		$TL_DIR/MakeTools/make_src_tar.sh \
+			"${RELEASE_TYPE}" \
+			"${TL_DIR}" \
+			"$USE_UNIFDEF" \
+			"$RPMDIR/SOURCES/opa-fm.tar.gz" \
+			"$FILES_TO_TAR" \
+			" -X tar_exc_pattern " \
+			"--transform=s,$PROJ_FILE_DIR/debian,debian," \
+		|| exit 1
+		(
+			export BUILD_ARGS="$args"
+			cd $RPMDIR
+			rpmbuild -ba --define "_topdir $RPMDIR" SPECS/opa-fm.spec
+		) || exit 1
+	else
+		RPMDIR="$TL_DIR/debbuild"
+		RPMVER=${RPM_VER}-${RPM_REL}
+		mkdir -p $RPMDIR/{build,dists}
 
-	(
-		export BUILD_ARGS="$args"
-		cd $RPMDIR
-		rpmbuild -ba --define "_topdir $RPMDIR" SPECS/opa-fm.spec
-	) || exit 1
-
+		OPAFM_SOURCE_TARBALL="$RPMDIR/dists/opa-fm.tar.gz"
+		# Create source tar ball. Update licenses if needed.
+		$TL_DIR/MakeTools/make_src_tar.sh \
+			"${RELEASE_TYPE}" \
+			"${TL_DIR}" \
+			"$USE_UNIFDEF" \
+			"$OPAFM_SOURCE_TARBALL" \
+			"$FILES_TO_TAR" \
+			" -X tar_exc_pattern " \
+			" --transform=s,$PROJ_FILE_DIR/debian,debian," \
+		|| exit 1
+		(
+			OPAFM_DIR="$RPMDIR/build/opa-fm-$RPM_VER"
+			mkdir -p "$OPAFM_DIR"
+			cd "$OPAFM_DIR"
+			tar xzf "$OPAFM_SOURCE_TARBALL"
+			# Prepate manifest from template
+			mv debian/changelog.in debian/changelog
+			# Annotate changelog file to get proper version
+			debchange --newversion=$RPMVER "Bump up version to $RPMVER"
+			# Pass build variables into package build environment
+			export BUILD_ARGS="$args"
+			dpkg-buildpackage -us -uc
+		) || exit 1
+	fi
 	make final_package
+	echo "$TL_DIR/$PROJ_FILE_DIR/$FEATURE_SETTINGS_FILE" >> packaged_files
 fi
 
 exit 0
