Import Upstream version 10.9.2.0-7

diff --git a/Esm/runmake b/Esm/runmake
--- a/Esm/runmake
+++ b/Esm/runmake
@@ -1,7 +1,7 @@
 #!/bin/bash
 # BEGIN_ICS_COPYRIGHT8 ****************************************
 # 
-# Copyright (c) 2015, Intel Corporation
+# Copyright (c) 2015-2017, Intel Corporation
 # 
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
@@ -202,9 +202,25 @@ then
 fi
 
 echo "---------------------------------------"
+# Import OPA Build feature settings.
+export OPA_FEATURE_SET=${OPA_FEATURE_SET:-$(cat $TL_DIR/$PROJ_FILE_DIR/DEFAULT_OPA_FEATURE_SET)}
+FEATURE_SETTINGS_FILE=opa_feature_settings.${PRODUCT}.$BUILD_CONFIG
+$TL_DIR/OpaBuildFeatureToggles/opa_build_import_feature_settings.sh
+if [ -e ./$FEATURE_SETTINGS_FILE ]; then
+	. ./$FEATURE_SETTINGS_FILE
+else
+	echo "$0: ERROR: OPA BUILD - $FEATURE_SETTINGS_FILE not found" >&2
+	exit 1
+fi
 showenv
 echo "---------------------------------------"
 
+# To run thew klocwork scans using klocwork_analyze script, it requires OPA_FEATURE_SET and BUILD_TARGET_OS_ID
+# Copying the required variables to $TL_DIR/$PRODUCT_DIRNAME/klocwork.env
+if [ "$KW_ENABLE" = "yes" ]; then
+	echo "export OPA_FEATURE_SET=${OPA_FEATURE_SET}" >> $TL_DIR/$PRODUCT_DIRNAME/klocwork.env
+	echo "export BUILD_TARGET_OS_ID=${BUILD_TARGET_OS_ID}" >> $TL_DIR/$PRODUCT_DIRNAME/klocwork.env
+fi
 echo "build for: $BUILD_TARGET"
 echo "Stack to build for: $BUILD_WITH_STACK ($OFED_STACK_PREFIX)"
 
@@ -219,9 +235,10 @@ then
 	exit 1
 fi
 
-MODULEVERSION=`$TL_DIR/MakeTools/convert_releasetag.pl $RELEASE_TAG`
-RPM_VER=`echo $MODULEVERSION|cut -d"." -f1-4`
-RPM_REL=`echo $MODULEVERSION.999.999.999.999|cut -d"." -f5`
+MODULEVERSION=`$TL_DIR/MakeTools/format_releasetag.py $RELEASE_TAG`
+RPMVERSION=`$TL_DIR/MakeTools/format_releasetag.py $RELEASE_TAG --format rpm`
+RPM_VER=`echo $RPMVERSION|cut -d"-" -f1`
+RPM_REL=`echo $RPMVERSION-999|cut -d"-" -f2`
 export MKRPM_VER=$RPM_VER
 export MKRPM_REL=$RPM_REL`rpm --eval %{?dist}`
 
@@ -241,11 +258,34 @@ then
 	#then
 		export REMOVE_DEPENDS=yes
 		make clobber clobber_stage clobber_release
+		(cd $TL_DIR/CommonInstall; make clobber_pl_files)
 		rm -f $TL_DIR/builtinplace.$PRODUCT.$BUILD_CONFIG
 	#fi
 fi
 
-rm -rf $TL_DIR/$PROJ_FILE_DIR/packaged_files $TL_DIR/$PROJ_FILE_DIR/dist_files
+rm -rf $TL_DIR/$PROJ_FILE_DIR/packaged_files $TL_DIR/$PROJ_FILE_DIR/dist_files $TL_DIR/Fd/buildFeatureDefs
+
+
+# make sure buildFeatureDefs is in place for the build
+make -f Makefile.linux $TL_DIR/Fd/buildFeatureDefs || exit 1
+
+# make sure opafm_src.xml is in place for the build
+(cd ib/src/linux/startup;make opafm_src.xml) || exit 1
+
+# make sure files from BaseFiles are in place
+while read comp fn
+do
+	if ! echo $comp | grep HFM > /dev/null
+	then
+		continue
+	fi
+	dir=$(dirname $fn)
+	bn=$(basename $fn)
+	(cd $TL_DIR/$dir;make $bn) || exit 1
+done < $TL_DIR/Fd/BaseFiles
+
+# make sure CommonInstall files are in place
+#(cd $TL_DIR/CommonInstall; make clobber_pl_files fm_files)
 
 args=
 if [ "$inplace" = y ]
@@ -259,7 +299,7 @@ fi
 
 if [ "$rpm" = y ]
 then
-	USE_UNIFDEF=${USE_UNIFDEF:-"no"}
+	USE_UNIFDEF=${USE_UNIFDEF:-"yes"}
 	set -x
 
 	# Pass env variables to rpmbuild. In integration build,
@@ -273,6 +313,7 @@ then
 	echo "export RELEASE_TAG=${RELEASE_TAG}" >> build.env
 	echo "export BUILD_CONFIG=\${BUILD_CONFIG:-\"${BUILD_CONFIG}\"}" >> build.env
 	echo "export BUILD_WITH_STACK=${BUILD_WITH_STACK}" >> build.env
+	echo "export LDENVFS=${LDENVFS}" >> build.env
 
 	FILES_TO_TAR=
 	# if in-place build left builtbin, builtinclude and builtlibs, pick them up
@@ -286,27 +327,66 @@ then
 	done
 	FILES_TO_TAR="$FILES_TO_TAR -T tar_inc_srcs_all"
 
-	RPMDIR="$TL_DIR/rpmbuild"
-	mkdir -p $RPMDIR/{BUILD,SPECS,BUILDROOT,SOURCES,RPMS,SRPMS}
+	if [ "$BUILD_PLATFORM_OS_VENDOR" != "ubuntu" ]
+	then
+		RPMDIR="$TL_DIR/rpmbuild"
+		mkdir -p $RPMDIR/{BUILD,SPECS,BUILDROOT,SOURCES,RPMS,SRPMS}
 
-	# Update the spec file
-	cp opa-fm.spec.base opa-fm.spec
-	sed -i "s/^Version:.*/Version: ${RPM_VER}/g" opa-fm.spec
-	sed -i "s/^Release:.*/Release: ${RPM_REL}%{?dist}/g" opa-fm.spec
-	# update distro dependencies
-	./update_opa-fm_spec.sh
-	mv opa-fm.spec $RPMDIR/SPECS/
+		# Update the spec file
+		cp opa-fm.spec.base opa-fm.spec
+		sed -i "s/__RPM_VERSION/${RPM_VER}/g" opa-fm.spec
+		sed -i "s/__RPM_RELEASE/${RPM_REL}%{?dist}/g" opa-fm.spec
+		# update distro dependencies
+		./update_opa-fm_spec.sh
+		mv opa-fm.spec $RPMDIR/SPECS/
 
-	# Create source tar ball. Update licenses if needed.
-	$TL_DIR/MakeTools/make_src_tar.sh "${RELEASE_TYPE}" "${TL_DIR}" "$USE_UNIFDEF" "$RPMDIR/SOURCES/opa-fm.tar.gz" "$FILES_TO_TAR" " -X tar_exc_pattern" || exit 1
+		# Create source tar ball. Update licenses if needed.
+		$TL_DIR/MakeTools/make_src_tar.sh \
+			"${RELEASE_TYPE}" \
+			"${TL_DIR}" \
+			"$USE_UNIFDEF" \
+			"$RPMDIR/SOURCES/opa-fm.tar.gz" \
+			"$FILES_TO_TAR" \
+			" -X tar_exc_pattern " \
+			"--transform=s,$PROJ_FILE_DIR/debian,debian," \
+		|| exit 1
+		(
+			export BUILD_ARGS="$args"
+			cd $RPMDIR
+			rpmbuild -ba --define "_topdir $RPMDIR" SPECS/opa-fm.spec
+		) || exit 1
+	else
+		RPMDIR="$TL_DIR/debbuild"
+		RPMVER=${RPM_VER}-${RPM_REL}
+		mkdir -p $RPMDIR/{build,dists}
 
-	(
-		export BUILD_ARGS="$args"
-		cd $RPMDIR
-		rpmbuild -ba --define "_topdir $RPMDIR" SPECS/opa-fm.spec
-	) || exit 1
-
+		OPAFM_SOURCE_TARBALL="$RPMDIR/dists/opa-fm.tar.gz"
+		# Create source tar ball. Update licenses if needed.
+		$TL_DIR/MakeTools/make_src_tar.sh \
+			"${RELEASE_TYPE}" \
+			"${TL_DIR}" \
+			"$USE_UNIFDEF" \
+			"$OPAFM_SOURCE_TARBALL" \
+			"$FILES_TO_TAR" \
+			" -X tar_exc_pattern " \
+			" --transform=s,$PROJ_FILE_DIR/debian,debian," \
+		|| exit 1
+		(
+			OPAFM_DIR="$RPMDIR/build/opa-fm-$RPM_VER"
+			mkdir -p "$OPAFM_DIR"
+			cd "$OPAFM_DIR"
+			tar xzf "$OPAFM_SOURCE_TARBALL"
+			# Prepate manifest from template
+			mv debian/changelog.in debian/changelog
+			# Annotate changelog file to get proper version
+			debchange --newversion=$RPMVER "Bump up version to $RPMVER"
+			# Pass build variables into package build environment
+			export BUILD_ARGS="$args"
+			dpkg-buildpackage -us -uc
+		) || exit 1
+	fi
 	make final_package
+	echo "$TL_DIR/$PROJ_FILE_DIR/$FEATURE_SETTINGS_FILE" >> packaged_files
 fi
 
 exit 0
